server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://119.3.184.67:3306/competition
    username: verall
    password: V123456.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.file-upload-path}

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 3GB

web:
  file-upload-path: C:/competitionFile/
