server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://119.3.184.67:3306/competition
    username: verall
    password: V123456.
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
